### ISSUE TITLE
Suggestion: Filter out sounds from other bots

### ISSUE THREAD

**Issue by lmmfranco** [Rei-x/discord-speech-recognition#19]
Having a music/sound bot in the same channel can spam the speech recognition with useless requests. Would be nice to have a setting (or even by default) to ignore messages from bots.

**Comment by Rei-x** [comment]
You can make a pull request for this feature. Basically add checking if user is a bot in handleSpeechEvent (of course it's only my suggestion, you can figure out something by yourself)
https://github.com/Rei-x/discord-speech-recognition/blob/f5858d707b61ae4f413ec88f6104fb94e748b24b/src/bot/events/speech.ts#L27

How to check if user is a bot?
```javascript
client.users.cache.get(userId).bot // returns true when user is a bot
```

To add another options to bot modify this interface:
https://github.com/Rei-x/discord-speech-recognition/blob/f5858d707b61ae4f413ec88f6104fb94e748b24b/src/bot/speechOptions.ts#L13-L21

Here you can specify default options:
https://github.com/Rei-x/discord-speech-recognition/blob/f5858d707b61ae4f413ec88f6104fb94e748b24b/src/bot/addSpeechEvent.ts#L22-L26

I will be more than happy to review your PR and also by contributing to this repository you will get a chance to win a t-shirt in hacktoberfest event - read more here https://hacktoberfest.digitalocean.com/

**Comment by Rei-x** [comment]
Added in #25
