### ISSUE TITLE
DiscordAPIError: Cannot send an empty message

### ISSUE THREAD

**Issue by cjlora** [Rei-x/discord-speech-recognition#32]
Hi there, I was trying out the simpleBot example and the bot crashes when it doesn't recognize a familiar word. I see that it throws something on traceback but it still stops the whole bot from functioning. I would really like to understand the code more and possibly put a try catch method so it prevents it from crashing. Thanks!

**Comment by cjlora** [comment]
It seemed to not crash anymore, however it started to repeat the message multiple times

![image](https://user-images.githubusercontent.com/66250459/178955306-0670afda-deb9-490b-b779-cb6fe3d78268.png)

**Comment by Rei-x** [comment]
okay, simpleBot was using outdated version of discord-speech-recognition, it should work now

**Comment by cjlora** [comment]
Yeah my bad, I didn't update it on my end. Apparently it outputs the message only once now, but it still seems to crash when it picks up inaudible sounds.

Here's the link to the repository: https://github.com/cjlora/tyrant-bot

**Comment by Rei-x** [comment]
you need to check if message is empty (because sometimes bot doesn't recognize speech properly) -> 
https://github.com/Rei-x/discord-speech-recognition/blob/main/examples/simpleBot/index.js#L27

```js
client.on("speech", (msg) => {
  if (!msg.content) return; // <- add this
  [some code]
});
```

**Comment by cjlora** [comment]
Okay, I'll try it out. Thanks dude!

**Comment by Rei-x** [comment]
no problem, if it works please close this issue and don't hesitate to ask if you have any more questions, have fun coding

**Comment by cjlora** [comment]
I'm having a weird interaction when a certain person joins the channel however I don't know how to troubleshoot it. Here's the traceback.

![image](https://user-images.githubusercontent.com/66250459/178965820-decb09eb-01d2-4bb3-a2d0-ced59f559318.png)

**Comment by Rei-x** [comment]
is this person using web version of discord?

**Comment by cjlora** [comment]
Yes the person is using a web version of discord.

**Comment by Rei-x** [comment]
unfortunately, I don't think that I can do anything with it, it's because of how @discordjs/voice handles voice connections, there is an open issue for this:
https://github.com/discordjs/discord.js/issues/7647

and there is also open pull request, i think it should be fixed relatively quickly:
https://github.com/discordjs/discord.js/pull/8277
