### ISSUE TITLE
OUT_OF_RANGE error

### ISSUE THREAD

**Issue by GeavaPapi** [Rei-x/discord-speech-recognition#33]
What's this
[https://cdn.discordapp.com/attachments/874431116533178459/998561381571903569/unknown.png](https://cdn.discordapp.com/attachments/874431116533178459/998561381571903569/unknown.png)

**Comment by Rei-x** [comment]
update `@discordjs/voice` package, it was fixed here: https://github.com/discordjs/discord.js/pull/8277
