### ISSUE TITLE
Error on trying to install the package.

### ISSUE THREAD

**Issue by MrF1yn** [Rei-x/discord-speech-recognition#42]
npm i discord-speech-recognition
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: minecraft-jarvis@1.0.0
npm ERR! Found: @discordjs/voice@0.13.0
npm ERR! node_modules/@discordjs/voice
npm ERR!   @discordjs/voice@"^0.13.0" from the root project
npm ERR!
npm ERR! peer @discordjs/voice@"^0.11.x" from discord-speech-recognition@3.1.0
npm ERR! node_modules/discord-speech-recognition
npm ERR!   discord-speech-recognition@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\GT-ACE\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GT-ACE\AppData\Local\npm-cache\_logs\2022-10-28T17_24_28_802Z-debug-0.log

**Comment by Mach1neCoder** [comment]
I am having the same error!

**Comment by Rei-x** [comment]
Should be fixed now #44
