### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mach1neCoder** [Rei-x/discord-speech-recognition#43]
> npm ERR! code 1
> npm ERR! path /home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus
> npm ERR! command failed
> npm ERR! command sh -c node-pre-gyp install --fallback-to-build
> npm ERR! Failed to execute '/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/bin/node /nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.34/opus.node --module_name=opus --module_path=/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.34 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
> npm ERR! node-pre-gyp info it worked if it ends with ok
> npm ERR! node-pre-gyp info using node-pre-gyp@0.4.5
> npm ERR! node-pre-gyp info using node@16.15.0 | linux | x64
> npm ERR! node-pre-gyp info check checked for "/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.34/opus.node" (not found)
> npm ERR! node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.8.0/opus-v0.8.0-node-v93-napi-v3-linux-x64-glibc-2.34.tar.gz
> npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.8.0/opus-v0.8.0-node-v93-napi-v3-linux-x64-glibc-2.34.tar.gz 
> npm ERR! node-pre-gyp WARN Pre-built binaries not installable for @discordjs/opus@0.8.0 and node@16.15.0 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) 
> npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/discordjs/opus/releases/download/v0.8.0/opus-v0.8.0-node-v93-napi-v3-linux-x64-glibc-2.34.tar.gz 
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.0.0
> npm ERR! gyp info using node@16.15.0 | linux | x64
> npm ERR! gyp info ok 
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.0.0
> npm ERR! gyp info using node@16.15.0 | linux | x64
> npm ERR! gyp ERR! find Python 
> npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
> npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
> npm ERR! gyp ERR! find Python checking if "python3" can be used
> npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
> npm ERR! gyp ERR! find Python checking if "python" can be used
> npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
> npm ERR! gyp ERR! find Python 
> npm ERR! gyp ERR! find Python **********************************************************
> npm ERR! gyp ERR! find Python You need to install the latest version of Python.
> npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
> npm ERR! gyp ERR! find Python you can try one of the following options:
> npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
> npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
> npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
> npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
> npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
> npm ERR! gyp ERR! find Python For more information consult the documentation at:
> npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
> npm ERR! gyp ERR! find Python **********************************************************
> npm ERR! gyp ERR! find Python 
> npm ERR! gyp ERR! configure error 
> npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
> npm ERR! gyp ERR! stack     at PythonFinder.fail (/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
> npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
> npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
> npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
> npm ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
> npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
> npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
> npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
> npm ERR! gyp ERR! System Linux 5.15.0-1021-gcp
> npm ERR! gyp ERR! command "/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/bin/node" "/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.34/opus.node" "--module_name=opus" "--module_path=/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.34" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
> npm ERR! gyp ERR! cwd /home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus
> npm ERR! gyp ERR! node -v v16.15.0
> npm ERR! gyp ERR! node-gyp -v v9.0.0
> npm ERR! gyp ERR! not ok 
> npm ERR! node-pre-gyp ERR! build error 
> npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/bin/node /nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.34/opus.node --module_name=opus --module_path=/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.34 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:85:20)
> npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
> npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
> npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
> npm ERR! node-pre-gyp ERR! System Linux 5.15.0-1021-gcp
> npm ERR! node-pre-gyp ERR! command "/nix/store/amm5j0ag985nh49n096a78q1dfs2xsfn-nodejs-16.15.0/bin/node" "/home/runner/LAST-TEST-I-SWEAR/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
> npm ERR! node-pre-gyp ERR! cwd /home/runner/LAST-TEST-I-SWEAR/node_modules/@discordjs/opus
> npm ERR! node-pre-gyp ERR! node -v v16.15.0
> npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.4.5
> npm ERR! node-pre-gyp ERR! not ok
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/runner/.npm/_logs/2022-11-04T00_06_26_657Z-debug-0.log

**Comment by Rei-x** [comment]
you need to install python:
https://www.python.org/downloads/
