### ISSUE TITLE
I keep getting this in visual studio code

### ISSUE THREAD

**Issue by CallmeJavier** [Rei-x/discord-speech-recognition#45]
ERR! Missing script: "start"
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:

**Comment by Rei-x** [comment]
what are you trying to run?
