### ISSUE TITLE
Audio BASE64 Output

### ISSUE THREAD

**Issue by Pudochu** [Rei-x/discord-speech-recognition#48]
Hello,

First of all, your module and project are very cool. I am using discord.js@v14 module and discord-speech-recognition latest version.

**My problem is is there any way I can get "audio base64" data with speech client event?**
```js
client.on("speech", (msg) => {
  // If bot didn't recognize speech, content will be empty
  if (!msg.content) return;

  msg.author.send(msg.content);
});
``` 

Kind regards,
Pudochu.

**Comment by Rei-x** [comment]
Hello, you can get raw PCM audio encoded to base64 like this:
```ts
client.on("speech", (msg) => {
    const rawAudioAsBase64 = msg.audioBuffer.toString("base64");
});
```
In case you want to play it in the browser on send to some API I added function to get wav data encoded as base64 (available in 3.2.0 version):
```ts
client.on("speech", (msg) => {
    const wavEncodedAsBase64 = msg.getWavEncodedToBase64Audio();
});
```
Is this what you want?

**Comment by Pudochu** [comment]
Hello, This is what I was looking for! I'm grateful for your help! Thanks so much.


```js
client.on("speech", (msg) => {
    const wavEncodedAsBase64 = msg.getWavEncodedToBase64Audio();
});
```
However, when I convert it to wav file, the sound is robotic and in slow motion.

Sincerely,
Pudochu.

**Comment by Pudochu** [comment]
Hello, i fixed.

```js
VoiceMessage.audioBufferFormat = {
    sampleRate: 48000,
    frameSize: 960,
    channels: 2,
};
```
