### ISSUE TITLE
Recognition stops after a while

### ISSUE THREAD

**Issue by KamilDrozd1136** [Rei-x/discord-speech-recognition#49]
Hi, I used the code some time ago and everything worked fine, now the speech recognition works as if for a while after the bot joins the voice channel, after that it stops sending responses. After I disconnect the bot from the channel and rejoin it again it works again for a while

**Comment by KamilDrozd1136** [comment]
I think an equal minute

**Comment by Naozumi520** [comment]
Yes, I got this issue also

**Comment by Rei-x** [comment]
okay, this is an issue with @discordjs/voice package, you can read more here https://github.com/discordjs/discord.js/issues/9185

i will add a temporary workaround for this

**Comment by Rei-x** [comment]
should be fixed now in 3.3.1, check if it works for you

**Comment by Naozumi520** [comment]
Yes, it works! Thank you. 😊
