### ISSUE TITLE
Short words are not detectable

### ISSUE THREAD

**Issue by Naozumi520** [Rei-x/discord-speech-recognition#50]
Some words like `Hi` and `really` are not detectable, and I didn't see any option to filter short words.

**Comment by Rei-x** [comment]
ah, yes, it was hardcoded so voice messages shorter than 1 seconds are ignored to avoid too many requests
https://github.com/Rei-x/discord-speech-recognition/blob/076bdc0a6e2aad338e558dc252dd7862a3b5404b/src/bot/voiceMessage/createVoiceMessage.ts#L28

I will add soon option to override it

**Comment by Rei-x** [comment]
added in v3.3.0

**Comment by Naozumi520** [comment]
I tried to put ```js
addSpeechEvent(client, {
    minimalVoiceMessageDuration: 1,
})
```

But it did not detect anything

**Comment by Rei-x** [comment]
change it to lower value, like 0.5 or 0.3, experiment with it until you get what you like
