### ISSUE TITLE
Option for changing base language?

### ISSUE THREAD

**Issue by molesquirrel** [Rei-x/discord-speech-recognition#53]
I saw an earlier issue regarding language support, but more simply, is there a way to set the default language (or multiple languages) used for the speech recognition?

**Comment by Narco121** [comment]
This is how you change the english default language: addSpeechEvent(client, { lang: "pl-PL" }). Make sure that the language format is correct for your desired language.

**Comment by Narco121** [comment]
This is how you change the english default language: `addSpeechEvent(client, { lang: "pl-PL" })`. Make sure that the language format is correct for your desired language.

**Comment by molesquirrel** [comment]
Thanks! I see the Google cloud at least appears to support multiple
languages at once; is there a known format for entering in more than one
language using the above advice?

**Comment by Narco121** [comment]
No you can only set one language at a time with english as the default language. If you want support for multiple languages, you have to customize the code yourself.
