### ISSUE TITLE
Change language after addSpeechEvent

### ISSUE THREAD

**Issue by Naozumi520** [Rei-x/discord-speech-recognition#57]
Is it possible to change the language after `addSpeechEvent`?

**Comment by Rei-x** [comment]
currently not, but it shouldn't be difficult for me to add it if you need it

**Comment by Naozumi520** [comment]
Please, I absolutely need this function 🙏
Thank you for your efforts!

**Comment by Narco121** [comment]
It would also be awesome if one could change the shouldProcessSpeech attribute for a user, after adding the speech event.

**Comment by AceHanded** [comment]
Changing the language afterwards would certainly be a big plus. Is there currently no workaround for doing that?
