### ISSUE TITLE
Recognizing voice input from DisTube's voice connection

### ISSUE THREAD

**Issue by AceHanded** [Rei-x/discord-speech-recognition#58]
I know someone has previously reported a problem with voice recognition when using another library for connecting to voice, however the solution presented in that thread (uninstalling the `@discordjs/voice` package), doesn't seem to work for the DisTube library, when using its `distube.voices.join(voiceChannel)` method and setting the deafened status to false. The bot does join the voice channel correctly, but the `client.on('speech')` event never gets emitted with that voice connection. Any help regarding this problem would be greatly appreciated!

**Comment by Rei-x** [comment]
Hello!

I think you need to pass bot user id to `group` in speechOptions
```javascript
addSpeechEvent(client, {
    group: client.user.id
});
```

Tell me if it fixed your issue!

**Comment by AceHanded** [comment]
Hi!

Thanks a million, that seemed to fix the issue :)
