### ISSUE TITLE
Google Speech to Text with Diarization?

### ISSUE THREAD

**Issue by davesienkowski** [Rei-x/discord-speech-recognition#60]
Do you know if it's possible, with your existing code, to add or enable the diarization config option for Google Speech to Text?

**Comment by Rei-x** [comment]
Hello! This library doesn't use Google Speech to Text from Google Cloud, just the old version of their speech api, that doesn't support it. 
Implementation was inspired by this [recognize_google](https://github.com/Uberi/speech_recognition/blob/8b07762f80dfec2d34fb4c40b8eddbb7ec503521/speech_recognition/__init__.py#L673-L742) function from python speech recognition package.

You can read more here about available options: https://github.com/gillesdemey/google-speech-v2

**Comment by davesienkowski** [comment]
Thank you for the reply as I'm a novice coder. I was having trouble differentiating between the multiple Google Speech to Text APIs. Wasn't sure which of the Google Speech to Text APIs was the latest so I appreciate you providing those links.
