### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by LMS5413** [Rei-x/discord-speech-recognition#8]
I'm using discord.js v13 but a package doesn't work. Could any developer help me?

**Comment by Rei-x** [comment]
I'm still working on v13 version, right now it's only compatible with v12 version. You can check progress on 2.0.0 branch. I'll publish new version on npm as soon as it's ready.

**Comment by LMS5413** [comment]
> I'm still working on v13 version, right now it's only compatible with v12 version. You can check progress on 2.0.0 branch. I'll publish new version on npm as soon as it's ready.

ah ok.
